#!/bin/bash

version="$1"
appName="ArtStationBot-v$version.app"
releasePath="Releases/$version"

# Set icons
cp ArtStationBot.icns $appName/Contents/Resources
cp ArtStationBot.icns $appName/Contents/Resources/applet.icns
cp Icon? $appName

# Update info.plist
cp Info.plist $appName/Contents

# Create release folder
mkdir -p $releasePath

# Copy contents to release folder
cp -R $appName $releasePath
cp artstation.js $releasePath
cp artstation-users.txt $releasePath
cp creds.txt $releasePath

# Archive the release
cd Releases
zip -r "ArtStationBot-v$version".zip $version -x "*.DS_Store"
rm -rf $version
cd ..

rm $appName
